// src/components/reports/ExpertReportEditor/ExpertReportEditor.tsx

"use client";

import {
    ArrowDown,
    ArrowLeft,
    ArrowUp,
    CircleAlert,
    Eye,
    EyeOff,
    FilePlus2,
    History,
    Loader2,
    Plus,
    Save,
    Trash2,
} from "lucide-react";
import Link from "next/link";
import {
    useCallback,
    useEffect,
    useMemo,
    useState,
} from "react";
import ExpertReportWorkflowActions from "@/components/reports/ExpertReportWorkflowActions/ExpertReportWorkflowActions";

import styles from "./styles.module.scss";

type ReportJsonValue =
    | string
    | number
    | boolean
    | null
    | ReportJsonValue[]
    | {
        [key: string]: ReportJsonValue;
    };

type ReportSectionType =
    | "COVER"
    | "IDENTIFICATION"
    | "PARTIES"
    | "EXPERTISE_OBJECT"
    | "CASE_SUMMARY"
    | "ANALYZED_DOCUMENTS"
    | "PREMISES"
    | "METHODOLOGY"
    | "INPUT_DATA"
    | "FORMULAS"
    | "CALCULATIONS"
    | "RESULTS"
    | "QUESTIONS"
    | "CONCLUSION"
    | "CLOSING"
    | "SIGNATURE"
    | "CUSTOM";

type ReportSection = {
    id?: string;
    type: ReportSectionType;
    title: string;
    plainText: string;
    content?: ReportJsonValue;
    position: number;
    isVisible: boolean;
    isAutoGenerated: boolean;
};

type ReportRevision = {
    id: string;
    version: number;
    status:
    | "DRAFT"
    | "IN_REVIEW"
    | "FINALIZED";

    title: string;
    reportNumber: string | null;
    purpose: string | null;
    referenceDate: string | null;
    place: string | null;
    notes: string | null;
    templateVersion: string;
    integrityHash: string | null;
    createdAt: string;
    updatedAt: string;
    sections: Array<{
        id: string;
        type: ReportSectionType;
        title: string;
        plainText: string | null;
        content: ReportJsonValue | null;
        position: number;
        isVisible: boolean;
        isAutoGenerated: boolean;
    }>;

    calculationLinks: Array<{
        calculation: {
            id: string;
            title: string | null;
            type: string;
        };

        calculationRevision: {
            id: string;
            version: number;
            engineVersion: string;
        };
    }>;
};

type ExpertReport = {
    id: string;
    title: string;
    reportNumber: string | null;
    status:
    | "DRAFT"
    | "IN_REVIEW"
    | "FINALIZED"
    | "ARCHIVED";

    purpose: string | null;
    referenceDate: string | null;
    place: string | null;
    currentVersion: number;
    revisions: ReportRevision[];
};

type ReportResponse = {
    report?: ExpertReport;
    message?: string;
};

type ExpertReportEditorProps = {
    reportId: string;
};

function formatDateInput(
    value: string | null,
) {
    if (!value) {
        return "";
    }

    const date = new Date(value);

    if (
        Number.isNaN(date.getTime())
    ) {
        return "";
    }

    return date
        .toISOString()
        .slice(0, 10);
}

function getStatusLabel(
    status:
        | "DRAFT"
        | "IN_REVIEW"
        | "FINALIZED"
        | "ARCHIVED",
) {
    const labels = {
        DRAFT: "Rascunho",
        IN_REVIEW: "Em revisão",
        FINALIZED: "Finalizado",
        ARCHIVED: "Arquivado",
    };

    return labels[status];
}

export default function ExpertReportEditor({
    reportId,
}: ExpertReportEditorProps) {
    const [
        report,
        setReport,
    ] =
        useState<ExpertReport | null>(
            null,
        );

    const [
        title,
        setTitle,
    ] = useState("");

    const [
        reportNumber,
        setReportNumber,
    ] = useState("");

    const [
        purpose,
        setPurpose,
    ] = useState("");

    const [
        referenceDate,
        setReferenceDate,
    ] = useState("");

    const [
        place,
        setPlace,
    ] = useState("");

    const [
        notes,
        setNotes,
    ] = useState("");

    const [
        sections,
        setSections,
    ] = useState<ReportSection[]>(
        [],
    );

    const [
        isLoading,
        setIsLoading,
    ] = useState(true);

    const [
        isSaving,
        setIsSaving,
    ] = useState(false);

    const [
        errorMessage,
        setErrorMessage,
    ] = useState("");

    const [
        successMessage,
        setSuccessMessage,
    ] = useState("");

    const currentRevision =
        useMemo(() => {
            if (!report) {
                return null;
            }

            return (
                report.revisions.find(
                    (revision) =>
                        revision.version ===
                        report.currentVersion,
                ) ??
                report.revisions[0] ??
                null
            );
        }, [report]);

    const loadReport =
        useCallback(async () => {
            setIsLoading(true);
            setErrorMessage("");

            try {
                const response =
                    await fetch(
                        `/api/reports/${encodeURIComponent(
                            reportId,
                        )}`,
                        {
                            method: "GET",
                            cache: "no-store",
                        },
                    );

                const payload =
                    (await response.json()) as ReportResponse;

                if (
                    !response.ok ||
                    !payload.report
                ) {
                    throw new Error(
                        payload.message ??
                        "Não foi possível carregar o laudo.",
                    );
                }

                const loadedReport =
                    payload.report;

                const loadedRevision =
                    loadedReport.revisions.find(
                        (revision) =>
                            revision.version ===
                            loadedReport.currentVersion,
                    ) ??
                    loadedReport.revisions[0];

                if (!loadedRevision) {
                    throw new Error(
                        "A revisão atual do laudo não foi encontrada.",
                    );
                }

                setReport(loadedReport);

                setTitle(
                    loadedRevision.title,
                );

                setReportNumber(
                    loadedRevision.reportNumber ??
                    "",
                );

                setPurpose(
                    loadedRevision.purpose ??
                    "",
                );

                setReferenceDate(
                    formatDateInput(
                        loadedRevision.referenceDate,
                    ),
                );

                setPlace(
                    loadedRevision.place ??
                    "",
                );

                setNotes(
                    loadedRevision.notes ??
                    "",
                );

                setSections(
                    loadedRevision.sections
                        .sort(
                            (left, right) =>
                                left.position -
                                right.position,
                        )
                        .map(
                            (
                                section,
                                index,
                            ) => ({
                                id: section.id,

                                type:
                                    section.type,

                                title:
                                    section.title,

                                plainText:
                                    section.plainText ??
                                    "",

                                content:
                                    section.content ??
                                    undefined,

                                position:
                                    index,

                                isVisible:
                                    section.isVisible,

                                isAutoGenerated:
                                    section.isAutoGenerated,
                            }),
                        ),
                );
            } catch (error) {
                setReport(null);

                setErrorMessage(
                    error instanceof Error
                        ? error.message
                        : "Não foi possível carregar o laudo.",
                );
            } finally {
                setIsLoading(false);
            }
        }, [reportId]);

    useEffect(() => {
        void loadReport();
    }, [loadReport]);

    function updateSection(
        index: number,
        changes: Partial<ReportSection>,
    ) {
        setSuccessMessage("");

        setSections(
            (current) =>
                current.map(
                    (section, position) =>
                        position === index
                            ? {
                                ...section,
                                ...changes,
                            }
                            : section,
                ),
        );
    }

    function moveSection(
        index: number,
        direction: -1 | 1,
    ) {
        const targetIndex =
            index + direction;

        if (
            targetIndex < 0 ||
            targetIndex >=
            sections.length
        ) {
            return;
        }

        setSuccessMessage("");

        setSections(
            (current) => {
                const updated = [
                    ...current,
                ];

                const [
                    selectedSection,
                ] = updated.splice(
                    index,
                    1,
                );

                updated.splice(
                    targetIndex,
                    0,
                    selectedSection,
                );

                return updated.map(
                    (section, position) => ({
                        ...section,
                        position,
                    }),
                );
            },
        );
    }

    function addCustomSection() {
        setSuccessMessage("");

        setSections(
            (current) => [
                ...current,
                {
                    type: "CUSTOM",
                    title: `${current.length + 1
                        }. Nova seção`,
                    plainText: "",
                    position:
                        current.length,
                    isVisible: true,
                    isAutoGenerated: false,
                },
            ],
        );
    }

    function removeSection(
        index: number,
    ) {
        setSuccessMessage("");

        setSections(
            (current) =>
                current
                    .filter(
                        (
                            _section,
                            position,
                        ) =>
                            position !==
                            index,
                    )
                    .map(
                        (
                            section,
                            position,
                        ) => ({
                            ...section,
                            position,
                        }),
                    ),
        );
    }

    async function saveReport(
        status:
            | "DRAFT"
            | "IN_REVIEW",
    ) {
        if (!title.trim()) {
            setErrorMessage(
                "Informe o título do laudo.",
            );

            return;
        }

        if (sections.length === 0) {
            setErrorMessage(
                "O laudo precisa possuir pelo menos uma seção.",
            );

            return;
        }

        setIsSaving(true);
        setErrorMessage("");
        setSuccessMessage("");

        try {
            const response =
                await fetch(
                    `/api/reports/${encodeURIComponent(
                        reportId,
                    )}`,
                    {
                        method: "PATCH",

                        headers: {
                            "Content-Type":
                                "application/json",
                        },

                        body: JSON.stringify({
                            title:
                                title.trim(),

                            reportNumber:
                                reportNumber.trim() ||
                                undefined,

                            purpose:
                                purpose.trim() ||
                                undefined,

                            referenceDate:
                                referenceDate ||
                                undefined,

                            place:
                                place.trim() ||
                                undefined,

                            notes:
                                notes.trim() ||
                                undefined,

                            status,

                            sections:
                                sections.map(
                                    (
                                        section,
                                        index,
                                    ) => ({
                                        id:
                                            section.id,

                                        type:
                                            section.type,

                                        title:
                                            section.title.trim() ||
                                            `Seção ${index + 1}`,

                                        plainText:
                                            section.plainText.trim() ||
                                            undefined,

                                        content:
                                            section.content,

                                        position:
                                            index,

                                        isVisible:
                                            section.isVisible,

                                        isAutoGenerated:
                                            section.isAutoGenerated,
                                    }),
                                ),
                        }),
                    },
                );

            const payload =
                (await response.json()) as ReportResponse;

            if (!response.ok) {
                throw new Error(
                    payload.message ??
                    "Não foi possível salvar o laudo.",
                );
            }

            setSuccessMessage(
                status === "IN_REVIEW"
                    ? "Laudo salvo e encaminhado para revisão."
                    : "Rascunho salvo com sucesso.",
            );

            await loadReport();
        } catch (error) {
            setErrorMessage(
                error instanceof Error
                    ? error.message
                    : "Não foi possível salvar o laudo.",
            );
        } finally {
            setIsSaving(false);
        }
    }

    if (isLoading) {
        return (
            <section
                className={
                    styles.loadingState
                }
            >
                <Loader2
                    className={
                        styles.spin
                    }
                    size={34}
                />

                <strong>
                    Carregando o laudo...
                </strong>
            </section>
        );
    }

    if (
        !report ||
        !currentRevision
    ) {
        return (
            <section
                className={
                    styles.errorState
                }
            >
                <CircleAlert size={36} />

                <strong>
                    Laudo não encontrado
                </strong>

                <p>{errorMessage}</p>

                <Link href="/historico">
                    <ArrowLeft size={17} />
                    Voltar ao histórico
                </Link>
            </section>
        );
    }

    const calculationId =
        currentRevision
            .calculationLinks[0]
            ?.calculation.id;

    const isReadOnly =
        report.status ===
        "FINALIZED" ||
        report.status ===
        "ARCHIVED" ||
        currentRevision.status ===
        "FINALIZED";

    return (
        <div
            className={
                styles.container
            }
        >
            <section
                className={
                    styles.summaryCard
                }
            >
                <div
                    className={
                        styles.summaryHeader
                    }
                >
                    <div>
                        <span
                            className={
                                styles.statusBadge
                            }
                            data-status={
                                report.status
                            }
                        >
                            {getStatusLabel(
                                report.status,
                            )}
                        </span>

                        <h2>{report.title}</h2>

                        <p>
                            Revisão{" "}
                            {
                                currentRevision.version
                            }{" "}
                            · Modelo{" "}
                            {
                                currentRevision.templateVersion
                            }
                        </p>
                    </div>

                    <div
                        className={
                            styles.summaryActions
                        }
                    >
                        {calculationId && (
                            <Link
                                href={`/historico/${encodeURIComponent(
                                    calculationId,
                                )}`}
                            >
                                <ArrowLeft
                                    size={16}
                                />

                                Voltar ao cálculo
                            </Link>
                        )}
                    </div>
                </div>

                <div
                    className={
                        styles.summaryGrid
                    }
                >
                    <div>
                        <span>
                            Revisão atual
                        </span>

                        <strong>
                            {
                                currentRevision.version
                            }
                        </strong>
                    </div>

                    <div>
                        <span>
                            Seções
                        </span>

                        <strong>
                            {sections.length}
                        </strong>
                    </div>

                    <div>
                        <span>
                            Cálculo utilizado
                        </span>

                        <strong>
                            {currentRevision
                                .calculationLinks[0]
                                ?.calculation.title ??
                                currentRevision
                                    .calculationLinks[0]
                                    ?.calculation.type ??
                                "Não informado"}
                        </strong>
                    </div>

                    <div>
                        <span>
                            Versão do cálculo
                        </span>

                        <strong>
                            {currentRevision
                                .calculationLinks[0]
                                ?.calculationRevision
                                .version ??
                                "—"}
                        </strong>
                    </div>
                </div>

                <div
                    className={
                        styles.hashBox
                    }
                >
                    <History size={17} />

                    <div>
                        <span>
                            Hash da revisão
                        </span>

                        <strong>
                            {currentRevision.integrityHash ??
                                "Ainda não gerado"}
                        </strong>
                    </div>
                </div>
            </section>

            <section
                className={
                    styles.metadataCard
                }
            >
                <div
                    className={
                        styles.cardTitle
                    }
                >
                    <span>
                        Dados gerais
                    </span>

                    <h3>
                        Identificação do documento
                    </h3>
                </div>

                <div
                    className={
                        styles.metadataFields
                    }
                >
                    <label
                        className={
                            styles.fullField
                        }
                    >
                        Título

                        <input
                            type="text"
                            value={title}
                            disabled={
                                isReadOnly
                            }
                            onChange={(event) =>
                                setTitle(
                                    event.target
                                        .value,
                                )
                            }
                        />
                    </label>

                    <div
                        className={
                            styles.twoColumns
                        }
                    >
                        <label>
                            Número do laudo

                            <input
                                type="text"
                                value={
                                    reportNumber
                                }
                                disabled={
                                    isReadOnly
                                }
                                onChange={(
                                    event,
                                ) =>
                                    setReportNumber(
                                        event
                                            .target
                                            .value,
                                    )
                                }
                            />
                        </label>

                        <label>
                            Data-base

                            <input
                                type="date"
                                value={
                                    referenceDate
                                }
                                disabled={
                                    isReadOnly
                                }
                                onChange={(
                                    event,
                                ) =>
                                    setReferenceDate(
                                        event
                                            .target
                                            .value,
                                    )
                                }
                            />
                        </label>
                    </div>

                    <label
                        className={
                            styles.fullField
                        }
                    >
                        Finalidade

                        <textarea
                            value={purpose}
                            disabled={
                                isReadOnly
                            }
                            rows={5}
                            onChange={(event) =>
                                setPurpose(
                                    event.target
                                        .value,
                                )
                            }
                        />
                    </label>

                    <label
                        className={
                            styles.fullField
                        }
                    >
                        Local

                        <input
                            type="text"
                            value={place}
                            disabled={
                                isReadOnly
                            }
                            onChange={(event) =>
                                setPlace(
                                    event.target
                                        .value,
                                )
                            }
                        />
                    </label>

                    <label
                        className={
                            styles.fullField
                        }
                    >
                        Observações internas

                        <textarea
                            value={notes}
                            disabled={
                                isReadOnly
                            }
                            rows={4}
                            onChange={(event) =>
                                setNotes(
                                    event.target
                                        .value,
                                )
                            }
                        />
                    </label>
                </div>
            </section>

            <section
                className={
                    styles.sectionsCard
                }
            >
                <div
                    className={
                        styles.sectionsHeader
                    }
                >
                    <div>
                        <span>
                            Estrutura do laudo
                        </span>

                        <h3>
                            Seções do documento
                        </h3>

                        <p>
                            O conteúdo matemático
                            automático permanece
                            vinculado à versão do
                            cálculo utilizada.
                        </p>
                    </div>

                    {!isReadOnly && (
                        <button
                            type="button"
                            onClick={
                                addCustomSection
                            }
                            className={
                                styles.addSectionButton
                            }
                        >
                            <Plus size={17} />
                            Nova seção
                        </button>
                    )}
                </div>

                <div
                    className={
                        styles.sectionList
                    }
                >
                    {sections.map(
                        (
                            section,
                            index,
                        ) => (
                            <article
                                key={
                                    section.id ??
                                    `${section.type}-${index}`
                                }
                                className={
                                    styles.sectionItem
                                }
                                data-hidden={
                                    !section.isVisible
                                }
                            >
                                <div
                                    className={
                                        styles.sectionToolbar
                                    }
                                >
                                    <div>
                                        <span>
                                            Seção{" "}
                                            {index + 1}
                                        </span>

                                        <small>
                                            {
                                                section.type
                                            }
                                            {section.isAutoGenerated
                                                ? " · conteúdo automático"
                                                : ""}
                                        </small>
                                    </div>

                                    {!isReadOnly && (
                                        <div
                                            className={
                                                styles.toolbarButtons
                                            }
                                        >
                                            <button
                                                type="button"
                                                disabled={
                                                    index ===
                                                    0
                                                }
                                                onClick={() =>
                                                    moveSection(
                                                        index,
                                                        -1,
                                                    )
                                                }
                                                aria-label="Mover seção para cima"
                                            >
                                                <ArrowUp
                                                    size={
                                                        15
                                                    }
                                                />
                                            </button>

                                            <button
                                                type="button"
                                                disabled={
                                                    index ===
                                                    sections.length -
                                                    1
                                                }
                                                onClick={() =>
                                                    moveSection(
                                                        index,
                                                        1,
                                                    )
                                                }
                                                aria-label="Mover seção para baixo"
                                            >
                                                <ArrowDown
                                                    size={
                                                        15
                                                    }
                                                />
                                            </button>

                                            <button
                                                type="button"
                                                onClick={() =>
                                                    updateSection(
                                                        index,
                                                        {
                                                            isVisible:
                                                                !section.isVisible,
                                                        },
                                                    )
                                                }
                                                aria-label={
                                                    section.isVisible
                                                        ? "Ocultar seção"
                                                        : "Exibir seção"
                                                }
                                            >
                                                {section.isVisible ? (
                                                    <Eye
                                                        size={
                                                            15
                                                        }
                                                    />
                                                ) : (
                                                    <EyeOff
                                                        size={
                                                            15
                                                        }
                                                    />
                                                )}
                                            </button>

                                            {section.type ===
                                                "CUSTOM" && (
                                                    <button
                                                        type="button"
                                                        className={
                                                            styles.deleteButton
                                                        }
                                                        onClick={() =>
                                                            removeSection(
                                                                index,
                                                            )
                                                        }
                                                        aria-label="Excluir seção"
                                                    >
                                                        <Trash2
                                                            size={
                                                                15
                                                            }
                                                        />
                                                    </button>
                                                )}
                                        </div>
                                    )}
                                </div>

                                <label>
                                    Título da seção

                                    <input
                                        type="text"
                                        value={
                                            section.title
                                        }
                                        disabled={
                                            isReadOnly
                                        }
                                        onChange={(
                                            event,
                                        ) =>
                                            updateSection(
                                                index,
                                                {
                                                    title:
                                                        event
                                                            .target
                                                            .value,
                                                },
                                            )
                                        }
                                    />
                                </label>

                                <label>
                                    Texto apresentado
                                    no laudo

                                    <textarea
                                        value={
                                            section.plainText
                                        }
                                        disabled={
                                            isReadOnly
                                        }
                                        rows={10}
                                        onChange={(
                                            event,
                                        ) =>
                                            updateSection(
                                                index,
                                                {
                                                    plainText:
                                                        event
                                                            .target
                                                            .value,
                                                },
                                            )
                                        }
                                    />
                                </label>
                            </article>
                        ),
                    )}
                </div>
            </section>

            {errorMessage && (
                <div
                    className={
                        styles.errorMessage
                    }
                >
                    <CircleAlert size={19} />
                    {errorMessage}
                </div>
            )}

            {successMessage && (
                <div
                    className={
                        styles.successMessage
                    }
                >
                    <Save size={19} />
                    {successMessage}
                </div>
            )}

            {!isReadOnly && (
                <div
                    className={
                        styles.actions
                    }
                >
                    <button
                        type="button"
                        className={
                            styles.draftButton
                        }
                        disabled={isSaving}
                        onClick={() =>
                            void saveReport(
                                "DRAFT",
                            )
                        }
                    >
                        {isSaving ? (
                            <Loader2
                                className={
                                    styles.spin
                                }
                                size={18}
                            />
                        ) : (
                            <Save size={18} />
                        )}

                        Salvar rascunho
                    </button>

                    <button
                        type="button"
                        className={
                            styles.reviewButton
                        }
                        disabled={isSaving}
                        onClick={() =>
                            void saveReport(
                                "IN_REVIEW",
                            )
                        }
                    >
                        {isSaving ? (
                            <Loader2
                                className={
                                    styles.spin
                                }
                                size={18}
                            />
                        ) : (
                            <FilePlus2
                                size={18}
                            />
                        )}

                        Salvar e colocar em revisão
                    </button>
                </div>
            )}

            <ExpertReportWorkflowActions
                reportId={
                    report.id
                }
                reportStatus={
                    report.status
                }
                revisionStatus={
                    currentRevision.status
                }
                revisionVersion={
                    currentRevision.version
                }
                onCompleted={
                    loadReport
                }
            />

        </div>
    );
}