-- CreateEnum
CREATE TYPE "ExpertReportRevisionStatus" AS ENUM ('DRAFT', 'IN_REVIEW', 'FINALIZED');

-- AlterTable
ALTER TABLE "GeneratedDocument" ADD COLUMN     "expertReportRevisionId" TEXT;

-- CreateTable
CREATE TABLE "ExpertReportRevision" (
    "id" TEXT NOT NULL,
    "expertReportId" TEXT NOT NULL,
    "createdById" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "status" "ExpertReportRevisionStatus" NOT NULL DEFAULT 'DRAFT',
    "title" TEXT NOT NULL,
    "reportNumber" TEXT,
    "purpose" TEXT,
    "referenceDate" TIMESTAMP(3),
    "place" TEXT,
    "issuedAt" TIMESTAMP(3),
    "templateVersion" TEXT NOT NULL DEFAULT 'expert-report-1.0.0',
    "sourceSnapshot" JSONB NOT NULL,
    "clientSnapshot" JSONB,
    "legalProcessSnapshot" JSONB,
    "professionalSnapshot" JSONB,
    "questionsSnapshot" JSONB,
    "sourceDocumentsSnapshot" JSONB,
    "integrityHash" TEXT,
    "notes" TEXT,
    "finalizedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ExpertReportRevision_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ExpertReportRevisionSection" (
    "id" TEXT NOT NULL,
    "expertReportRevisionId" TEXT NOT NULL,
    "type" "ReportSectionType" NOT NULL,
    "title" TEXT NOT NULL,
    "plainText" TEXT,
    "content" JSONB,
    "position" INTEGER NOT NULL,
    "isVisible" BOOLEAN NOT NULL DEFAULT true,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ExpertReportRevisionSection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ExpertReportRevisionCalculation" (
    "id" TEXT NOT NULL,
    "expertReportRevisionId" TEXT NOT NULL,
    "calculationId" TEXT NOT NULL,
    "calculationRevisionId" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "snapshot" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ExpertReportRevisionCalculation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ExpertReportRevision_expertReportId_idx" ON "ExpertReportRevision"("expertReportId");

-- CreateIndex
CREATE INDEX "ExpertReportRevision_createdById_idx" ON "ExpertReportRevision"("createdById");

-- CreateIndex
CREATE INDEX "ExpertReportRevision_status_idx" ON "ExpertReportRevision"("status");

-- CreateIndex
CREATE INDEX "ExpertReportRevision_createdAt_idx" ON "ExpertReportRevision"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "ExpertReportRevision_expertReportId_version_key" ON "ExpertReportRevision"("expertReportId", "version");

-- CreateIndex
CREATE INDEX "ExpertReportRevisionSection_expertReportRevisionId_idx" ON "ExpertReportRevisionSection"("expertReportRevisionId");

-- CreateIndex
CREATE INDEX "ExpertReportRevisionSection_type_idx" ON "ExpertReportRevisionSection"("type");

-- CreateIndex
CREATE INDEX "ExpertReportRevisionSection_position_idx" ON "ExpertReportRevisionSection"("position");

-- CreateIndex
CREATE UNIQUE INDEX "ExpertReportRevisionSection_expertReportRevisionId_position_key" ON "ExpertReportRevisionSection"("expertReportRevisionId", "position");

-- CreateIndex
CREATE INDEX "ExpertReportRevisionCalculation_expertReportRevisionId_idx" ON "ExpertReportRevisionCalculation"("expertReportRevisionId");

-- CreateIndex
CREATE INDEX "ExpertReportRevisionCalculation_calculationId_idx" ON "ExpertReportRevisionCalculation"("calculationId");

-- CreateIndex
CREATE INDEX "ExpertReportRevisionCalculation_calculationRevisionId_idx" ON "ExpertReportRevisionCalculation"("calculationRevisionId");

-- CreateIndex
CREATE INDEX "ExpertReportRevisionCalculation_position_idx" ON "ExpertReportRevisionCalculation"("position");

-- CreateIndex
CREATE UNIQUE INDEX "ExpertReportRevisionCalculation_expertReportRevisionId_calc_key" ON "ExpertReportRevisionCalculation"("expertReportRevisionId", "calculationRevisionId");

-- CreateIndex
CREATE INDEX "GeneratedDocument_expertReportRevisionId_idx" ON "GeneratedDocument"("expertReportRevisionId");

-- AddForeignKey
ALTER TABLE "ExpertReportRevision" ADD CONSTRAINT "ExpertReportRevision_expertReportId_fkey" FOREIGN KEY ("expertReportId") REFERENCES "ExpertReport"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExpertReportRevision" ADD CONSTRAINT "ExpertReportRevision_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "AppUserProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExpertReportRevisionSection" ADD CONSTRAINT "ExpertReportRevisionSection_expertReportRevisionId_fkey" FOREIGN KEY ("expertReportRevisionId") REFERENCES "ExpertReportRevision"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExpertReportRevisionCalculation" ADD CONSTRAINT "ExpertReportRevisionCalculation_expertReportRevisionId_fkey" FOREIGN KEY ("expertReportRevisionId") REFERENCES "ExpertReportRevision"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExpertReportRevisionCalculation" ADD CONSTRAINT "ExpertReportRevisionCalculation_calculationId_fkey" FOREIGN KEY ("calculationId") REFERENCES "Calculation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExpertReportRevisionCalculation" ADD CONSTRAINT "ExpertReportRevisionCalculation_calculationRevisionId_fkey" FOREIGN KEY ("calculationRevisionId") REFERENCES "CalculationRevision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GeneratedDocument" ADD CONSTRAINT "GeneratedDocument_expertReportRevisionId_fkey" FOREIGN KEY ("expertReportRevisionId") REFERENCES "ExpertReportRevision"("id") ON DELETE SET NULL ON UPDATE CASCADE;
