// src/components/reports/ExpertReportPreview/ExpertReportPreview.tsx

"use client";

import {
    ArrowLeft,
    CheckCircle2,
    CircleAlert,
    Download,
    FilePenLine,
    FileText,
    History,
    Loader2,
    Printer,
    ShieldCheck,
} from "lucide-react";
import Link from "next/link";
import {
    useCallback,
    useEffect,
    useMemo,
    useState,
} from "react";

import styles from "./styles.module.scss";

type JsonValue =
    | string
    | number
    | boolean
    | null
    | JsonValue[]
    | {
        [key: string]: JsonValue;
    };

type ReportStatus =
    | "DRAFT"
    | "IN_REVIEW"
    | "FINALIZED"
    | "ARCHIVED";

type RevisionStatus =
    | "DRAFT"
    | "IN_REVIEW"
    | "FINALIZED";

type ReportSectionType =
    | "COVER"
    | "IDENTIFICATION"
    | "PARTIES"
    | "EXPERTISE_OBJECT"
    | "CASE_SUMMARY"
    | "ANALYZED_DOCUMENTS"
    | "PREMISES"
    | "METHODOLOGY"
    | "INPUT_DATA"
    | "FORMULAS"
    | "CALCULATIONS"
    | "RESULTS"
    | "QUESTIONS"
    | "CONCLUSION"
    | "CLOSING"
    | "SIGNATURE"
    | "CUSTOM";

type ExportFormat =
    | "PDF"
    | "DOCX";

type ReportSection = {
    id: string;
    type: ReportSectionType;
    title: string;
    plainText: string | null;
    content: JsonValue | null;
    position: number;
    isVisible: boolean;
    isAutoGenerated: boolean;
};

type CalculationLineRecord =
    Record<string, JsonValue>;

type CalculationLink = {
    calculation: {
        id: string;
        type: string;
        title: string | null;
        description: string | null;
        currency: string;
        currentVersion: number;
    };

    calculationRevision: {
        id: string;
        version: number;
        engineVersion: string;
        integrityHash: string | null;
        lines: CalculationLineRecord[];
    };
};

type ReportRevision = {
    id: string;
    version: number;
    status: RevisionStatus;
    title: string;
    reportNumber: string | null;
    purpose: string | null;
    referenceDate: string | null;
    place: string | null;
    issuedAt: string | null;
    notes: string | null;
    templateVersion: string;
    integrityHash: string | null;
    createdAt: string;
    updatedAt: string;
    sections: ReportSection[];
    calculationLinks: CalculationLink[];
};

type ExpertReport = {
    id: string;
    title: string;
    reportNumber: string | null;
    status: ReportStatus;
    purpose: string | null;
    referenceDate: string | null;
    place: string | null;
    issuedAt: string | null;
    currentVersion: number;

    client: {
        id: string;
        name: string;
        tradeName: string | null;
        documentNumber: string | null;
    } | null;

    legalProcess: {
        id: string;
        caseNumber: string | null;
        title: string | null;
        court: string | null;
        courtDivision: string | null;
        city: string | null;
        state: string | null;
    } | null;

    revisions: ReportRevision[];
};

type ReportResponse = {
    report?: ExpertReport;
    message?: string;
};

type ExportErrorResponse = {
    message?: string;
    code?: string;
};

type ExpertReportPreviewProps = {
    reportId: string;
    requestedVersion?: number;
};

type ColumnKind =
    | "text"
    | "number"
    | "money"
    | "percent"
    | "date";

type LineColumn = {
    id: string;
    label: string;
    kind: ColumnKind;
    always?: boolean;

    getValue: (
        line: CalculationLineRecord,
    ) => JsonValue | undefined;
};

function normalizeType(type: string) {
    return type
        .trim()
        .toUpperCase()
        .replace(/[\s-]+/g, "_");
}

function isJsonRecord(
    value: unknown,
): value is Record<string, JsonValue> {
    return (
        value !== null &&
        typeof value === "object" &&
        !Array.isArray(value)
    );
}

function hasValue(
    value: JsonValue | undefined,
) {
    return (
        value !== undefined &&
        value !== null &&
        value !== ""
    );
}

function formatDate(
    value:
        | string
        | null
        | undefined,
) {
    if (!value) {
        return "Não informada";
    }

    const date = new Date(value);

    if (
        Number.isNaN(date.getTime())
    ) {
        return value;
    }

    return new Intl.DateTimeFormat(
        "pt-BR",
    ).format(date);
}

function formatDateTime(
    value:
        | string
        | null
        | undefined,
) {
    if (!value) {
        return "Não informado";
    }

    const date = new Date(value);

    if (
        Number.isNaN(date.getTime())
    ) {
        return value;
    }

    return new Intl.DateTimeFormat(
        "pt-BR",
        {
            dateStyle: "short",
            timeStyle: "short",
        },
    ).format(date);
}

function formatMoney(
    value: JsonValue | undefined,
    currency: string,
) {
    if (!hasValue(value)) {
        return "—";
    }

    const numericValue =
        Number(value);

    if (
        !Number.isFinite(
            numericValue,
        )
    ) {
        return String(value);
    }

    return new Intl.NumberFormat(
        "pt-BR",
        {
            style: "currency",
            currency,
        },
    ).format(numericValue);
}

function formatPercent(
    value: JsonValue | undefined,
) {
    if (!hasValue(value)) {
        return "—";
    }

    const numericValue =
        Number(value);

    if (
        !Number.isFinite(
            numericValue,
        )
    ) {
        return String(value);
    }

    const percentage =
        Math.abs(numericValue) <= 1
            ? numericValue * 100
            : numericValue;

    return `${new Intl.NumberFormat(
        "pt-BR",
        {
            minimumFractionDigits: 2,
            maximumFractionDigits: 6,
        },
    ).format(percentage)}%`;
}

function formatPrimitive(
    value: JsonValue | undefined,
) {
    if (!hasValue(value)) {
        return "—";
    }

    if (typeof value === "boolean") {
        return value
            ? "Sim"
            : "Não";
    }

    if (
        typeof value === "object"
    ) {
        return JSON.stringify(value);
    }

    return String(value);
}

function formatColumnValue(
    value: JsonValue | undefined,
    kind: ColumnKind,
    currency: string,
) {
    if (kind === "money") {
        return formatMoney(
            value,
            currency,
        );
    }

    if (kind === "percent") {
        return formatPercent(value);
    }

    if (kind === "date") {
        return typeof value === "string"
            ? formatDate(value)
            : "—";
    }

    if (kind === "number") {
        if (!hasValue(value)) {
            return "—";
        }

        const numericValue =
            Number(value);

        return Number.isFinite(
            numericValue,
        )
            ? new Intl.NumberFormat(
                "pt-BR",
            ).format(numericValue)
            : String(value);
    }

    return formatPrimitive(value);
}

function getMetadataValue(
    line: CalculationLineRecord,
    key: string,
) {
    const metadata =
        line.metadata;

    if (!isJsonRecord(metadata)) {
        return undefined;
    }

    return metadata[key];
}

function getCalculationLines(
    revision: ReportRevision,
    calculationsSection:
        | ReportSection
        | undefined,
) {
    if (
        calculationsSection &&
        isJsonRecord(
            calculationsSection.content,
        )
    ) {
        const storedLines =
            calculationsSection.content
                .lines;

        if (Array.isArray(storedLines)) {
            const parsedLines =
                storedLines.filter(
                    isJsonRecord,
                );

            if (
                parsedLines.length > 0
            ) {
                return parsedLines;
            }
        }
    }

    return revision.calculationLinks.flatMap(
        (link) =>
            link.calculationRevision
                .lines ?? [],
    );
}

function getLineColumns(
    calculationType: string,
    lines: CalculationLineRecord[],
): LineColumn[] {
    const normalizedType =
        normalizeType(
            calculationType,
        );

    let columns: LineColumn[];

    if (
        [
            "FLUXO_DE_CAIXA",
            "FLUXO_CAIXA",
        ].includes(normalizedType)
    ) {
        columns = [
            {
                id: "sequence",
                label: "#",
                kind: "number",
                always: true,

                getValue: (line) =>
                    line.sequence,
            },

            {
                id: "period",
                label: "Período",
                kind: "number",
                always: true,

                getValue: (line) =>
                    getMetadataValue(
                        line,
                        "period",
                    ),
            },

            {
                id: "label",
                label: "Descrição",
                kind: "text",
                always: true,

                getValue: (line) =>
                    line.label,
            },

            {
                id: "credit",
                label: "Entrada",
                kind: "money",

                getValue: (line) =>
                    line.credit,
            },

            {
                id: "debit",
                label: "Saída",
                kind: "money",

                getValue: (line) =>
                    line.debit,
            },

            {
                id: "openingBalance",
                label: "Saldo inicial",
                kind: "money",

                getValue: (line) =>
                    line.openingBalance,
            },

            {
                id: "closingBalance",
                label: "Saldo final",
                kind: "money",
                always: true,

                getValue: (line) =>
                    line.closingBalance,
            },
        ];
    } else if (
        normalizedType ===
        "ANALISE_PERICIAL"
    ) {
        columns = [
            {
                id: "sequence",
                label: "#",
                kind: "number",
                always: true,

                getValue: (line) =>
                    line.sequence,
            },

            {
                id: "label",
                label: "Etapa",
                kind: "text",
                always: true,

                getValue: (line) =>
                    line.label,
            },

            {
                id: "openingBalance",
                label: "Saldo inicial",
                kind: "money",

                getValue: (line) =>
                    line.openingBalance,
            },

            {
                id: "debit",
                label: "Adição",
                kind: "money",

                getValue: (line) =>
                    line.debit,
            },

            {
                id: "monetaryCorrection",
                label: "Correção",
                kind: "money",

                getValue: (line) =>
                    line.monetaryCorrection,
            },

            {
                id: "interest",
                label: "Juros",
                kind: "money",

                getValue: (line) =>
                    line.interest,
            },

            {
                id: "fine",
                label: "Multa",
                kind: "money",

                getValue: (line) =>
                    line.fine,
            },

            {
                id: "fee",
                label: "Honorários",
                kind: "money",

                getValue: (line) =>
                    line.fee,
            },

            {
                id: "payment",
                label: "Pagamento",
                kind: "money",

                getValue: (line) =>
                    line.payment ??
                    line.credit,
            },

            {
                id: "closingBalance",
                label: "Saldo final",
                kind: "money",
                always: true,

                getValue: (line) =>
                    line.closingBalance,
            },
        ];
    } else {
        columns = [
            {
                id: "sequence",
                label: "#",
                kind: "number",
                always: true,

                getValue: (line) =>
                    line.sequence,
            },

            {
                id: "label",
                label: "Descrição",
                kind: "text",
                always: true,

                getValue: (line) =>
                    line.label,
            },

            {
                id: "competence",
                label: "Competência",
                kind: "date",

                getValue: (line) =>
                    line.competence ??
                    line.dueDate,
            },

            {
                id: "openingBalance",
                label: "Saldo inicial",
                kind: "money",

                getValue: (line) =>
                    line.openingBalance,
            },

            {
                id: "correctionRate",
                label: "Correção %",
                kind: "percent",

                getValue: (line) =>
                    line.correctionRate,
            },

            {
                id: "monetaryCorrection",
                label: "Correção",
                kind: "money",

                getValue: (line) =>
                    line.monetaryCorrection,
            },

            {
                id: "interestRate",
                label: "Juros %",
                kind: "percent",

                getValue: (line) =>
                    line.interestRate,
            },

            {
                id: "interest",
                label: "Juros",
                kind: "money",

                getValue: (line) =>
                    line.interest,
            },

            {
                id: "amortization",
                label: "Amortização",
                kind: "money",

                getValue: (line) =>
                    line.amortization,
            },

            {
                id: "installment",
                label: "Prestação",
                kind: "money",

                getValue: (line) =>
                    line.installment,
            },

            {
                id: "payment",
                label: "Pagamento",
                kind: "money",

                getValue: (line) =>
                    line.payment,
            },

            {
                id: "closingBalance",
                label: "Saldo final",
                kind: "money",

                getValue: (line) =>
                    line.closingBalance,
            },
        ];
    }

    return columns.filter(
        (column) =>
            column.always ||
            lines.some((line) =>
                hasValue(
                    column.getValue(line),
                ),
            ),
    );
}

function getStatusLabel(
    status:
        | ReportStatus
        | RevisionStatus,
) {
    const labels = {
        DRAFT: "Rascunho",
        IN_REVIEW: "Em revisão",
        FINALIZED: "Finalizado",
        ARCHIVED: "Arquivado",
    };

    return labels[status];
}

function shortenHash(
    hash: string | null,
) {
    if (!hash) {
        return "Hash não disponível";
    }

    if (hash.length <= 24) {
        return hash;
    }

    return `${hash.slice(
        0,
        12,
    )}...${hash.slice(-12)}`;
}

function renderText(
    text: string | null,
) {
    if (!text?.trim()) {
        return (
            <p className={styles.emptyText}>
                Nenhum conteúdo informado nesta
                seção.
            </p>
        );
    }

    return (
        <div className={styles.sectionText}>
            {text}
        </div>
    );
}

function getFileNameFromHeader(
    contentDisposition: string | null,
    fallback: string,
) {
    if (!contentDisposition) {
        return fallback;
    }

    const utf8Match =
        contentDisposition.match(
            /filename\*=UTF-8''([^;]+)/i,
        );

    if (utf8Match?.[1]) {
        try {
            return decodeURIComponent(
                utf8Match[1],
            );
        } catch {
            return utf8Match[1];
        }
    }

    const simpleMatch =
        contentDisposition.match(
            /filename="?([^";]+)"?/i,
        );

    return simpleMatch?.[1] ??
        fallback;
}

async function getExportErrorMessage(
    response: Response,
    fallback: string,
) {
    const contentType =
        response.headers.get(
            "content-type",
        );

    if (
        contentType?.includes(
            "application/json",
        )
    ) {
        try {
            const payload =
                (await response.json()) as ExportErrorResponse;

            return (
                payload.message ??
                fallback
            );
        } catch {
            return fallback;
        }
    }

    try {
        const text =
            await response.text();

        return text.trim() ||
            fallback;
    } catch {
        return fallback;
    }
}

export default function ExpertReportPreview({
    reportId,
    requestedVersion,
}: ExpertReportPreviewProps) {
    const [
        report,
        setReport,
    ] =
        useState<ExpertReport | null>(
            null,
        );

    const [
        isLoading,
        setIsLoading,
    ] = useState(true);

    const [
        errorMessage,
        setErrorMessage,
    ] = useState("");

    const [
        exportingFormat,
        setExportingFormat,
    ] =
        useState<ExportFormat | null>(
            null,
        );

    const [
        exportError,
        setExportError,
    ] = useState("");

    const [
        exportSuccess,
        setExportSuccess,
    ] = useState("");

    const loadReport =
        useCallback(async () => {
            setIsLoading(true);
            setErrorMessage("");

            try {
                const response =
                    await fetch(
                        `/api/reports/${encodeURIComponent(
                            reportId,
                        )}`,
                        {
                            method: "GET",
                            cache: "no-store",
                        },
                    );

                const payload =
                    (await response.json()) as ReportResponse;

                if (
                    !response.ok ||
                    !payload.report
                ) {
                    throw new Error(
                        payload.message ??
                        "Não foi possível carregar o laudo.",
                    );
                }

                const loadedReport =
                    payload.report;

                if (
                    requestedVersion &&
                    !loadedReport.revisions.some(
                        (revision) =>
                            revision.version ===
                            requestedVersion,
                    )
                ) {
                    throw new Error(
                        `A revisão ${requestedVersion} do laudo não foi encontrada.`,
                    );
                }

                setReport(loadedReport);
            } catch (error) {
                setReport(null);

                setErrorMessage(
                    error instanceof Error
                        ? error.message
                        : "Não foi possível carregar o laudo.",
                );
            } finally {
                setIsLoading(false);
            }
        }, [
            reportId,
            requestedVersion,
        ]);

    useEffect(() => {
        void loadReport();
    }, [loadReport]);

    const selectedRevision =
        useMemo(() => {
            if (!report) {
                return null;
            }

            if (requestedVersion) {
                return (
                    report.revisions.find(
                        (revision) =>
                            revision.version ===
                            requestedVersion,
                    ) ?? null
                );
            }

            return (
                report.revisions.find(
                    (revision) =>
                        revision.version ===
                        report.currentVersion,
                ) ??
                report.revisions[0] ??
                null
            );
        }, [
            report,
            requestedVersion,
        ]);

    const visibleSections =
        useMemo(() => {
            if (!selectedRevision) {
                return [];
            }

            return [
                ...selectedRevision.sections,
            ]
                .filter(
                    (section) =>
                        section.isVisible,
                )
                .sort(
                    (left, right) =>
                        left.position -
                        right.position,
                );
        }, [selectedRevision]);

    if (isLoading) {
        return (
            <section
                className={
                    styles.loadingState
                }
            >
                <Loader2
                    className={
                        styles.spin
                    }
                    size={36}
                />

                <strong>
                    Montando visualização A4...
                </strong>

                <p>
                    Carregando seções, fórmulas e
                    memória do cálculo.
                </p>
            </section>
        );
    }

    if (
        !report ||
        !selectedRevision
    ) {
        return (
            <section
                className={
                    styles.errorState
                }
            >
                <CircleAlert
                    size={38}
                />

                <strong>
                    Laudo não encontrado
                </strong>

                <p>{errorMessage}</p>

                <Link href="/historico">
                    <ArrowLeft
                        size={17}
                    />

                    Voltar ao histórico
                </Link>
            </section>
        );
    }

    const coverSection =
        visibleSections.find(
            (section) =>
                section.type === "COVER",
        );

    const bodySections =
        visibleSections.filter(
            (section) =>
                section.type !== "COVER",
        );

    const calculationLink =
        selectedRevision
            .calculationLinks[0];

    const calculationType =
        calculationLink?.calculation
            .type ?? "";

    const currency =
        calculationLink?.calculation
            .currency ?? "BRL";

    const calculationsSection =
        bodySections.find(
            (section) =>
                section.type ===
                "CALCULATIONS",
        );

    const calculationLines =
        getCalculationLines(
            selectedRevision,
            calculationsSection,
        );

    const lineColumns =
        getLineColumns(
            calculationType,
            calculationLines,
        );

    const showDraftWatermark =
        report.status !==
        "FINALIZED" ||
        selectedRevision.status !==
        "FINALIZED";

    const encodedReportId =
        encodeURIComponent(report.id);

    const selectedRevisionVersion =
        selectedRevision.version;

    function handlePrint() {
        window.print();
    }

    async function handleExport(
        format: ExportFormat,
    ) {
        setExportingFormat(format);
        setExportError("");
        setExportSuccess("");

        const extension =
            format === "PDF"
                ? "pdf"
                : "docx";

        const fallbackFileName =
            `laudo-pericial-revisao-${selectedRevisionVersion}.${extension}`;

        try {
            const response =
                await fetch(
                    `/api/reports/${encodedReportId}/revisions/${selectedRevisionVersion}/export/${extension}`,
                    {
                        method: "GET",
                        cache: "no-store",
                    },
                );

            if (!response.ok) {
                const message =
                    await getExportErrorMessage(
                        response,
                        format === "PDF"
                            ? "Não foi possível gerar o arquivo PDF."
                            : "Não foi possível gerar o arquivo Word.",
                    );

                throw new Error(message);
            }

            const blob =
                await response.blob();

            if (blob.size === 0) {
                throw new Error(
                    "O arquivo gerado está vazio.",
                );
            }

            const fileName =
                getFileNameFromHeader(
                    response.headers.get(
                        "content-disposition",
                    ),
                    fallbackFileName,
                );

            const objectUrl =
                URL.createObjectURL(blob);

            const anchor =
                document.createElement(
                    "a",
                );

            anchor.href = objectUrl;
            anchor.download = fileName;
            anchor.style.display =
                "none";

            document.body.appendChild(
                anchor,
            );

            anchor.click();
            anchor.remove();

            window.setTimeout(() => {
                URL.revokeObjectURL(
                    objectUrl,
                );
            }, 1000);

            setExportSuccess(
                format === "PDF"
                    ? "Arquivo PDF gerado e enviado para download."
                    : "Arquivo Word gerado e enviado para download.",
            );
        } catch (error) {
            setExportError(
                error instanceof Error
                    ? error.message
                    : "Não foi possível exportar o laudo.",
            );
        } finally {
            setExportingFormat(null);
        }
    }

    return (
        <div
            className={
                styles.container
            }
        >
            <div
                className={
                    styles.toolbar
                }
            >
                <div
                    className={
                        styles.toolbarNavigation
                    }
                >
                    <Link
                        href={`/laudos/${encodedReportId}/editar`}
                        className={
                            styles.backButton
                        }
                    >
                        <ArrowLeft
                            size={17}
                        />

                        Voltar ao editor
                    </Link>

                    <div
                        className={
                            styles.previewStatus
                        }
                    >
                        <History
                            size={17}
                        />

                        <div>
                            <span>
                                Revisão visualizada
                            </span>

                            <strong>
                                Versão{" "}
                                {
                                    selectedRevision.version
                                }{" "}
                                ·{" "}
                                {getStatusLabel(
                                    selectedRevision.status,
                                )}
                            </strong>
                        </div>
                    </div>
                </div>

                <div
                    className={
                        styles.toolbarActions
                    }
                >
                    <Link
                        href={`/laudos/${encodedReportId}/editar`}
                        className={
                            styles.editButton
                        }
                    >
                        <FilePenLine
                            size={17}
                        />

                        Editar
                    </Link>

                    <button
                        type="button"
                        className={
                            styles.wordButton
                        }
                        disabled={
                            exportingFormat !==
                            null
                        }
                        onClick={() =>
                            void handleExport(
                                "DOCX",
                            )
                        }
                    >
                        {exportingFormat ===
                            "DOCX" ? (
                            <Loader2
                                className={
                                    styles.spin
                                }
                                size={17}
                            />
                        ) : (
                            <FileText
                                size={17}
                            />
                        )}

                        {exportingFormat ===
                            "DOCX"
                            ? "Gerando Word..."
                            : "Baixar Word"}
                    </button>

                    <button
                        type="button"
                        className={
                            styles.pdfButton
                        }
                        disabled={
                            exportingFormat !==
                            null
                        }
                        onClick={() =>
                            void handleExport(
                                "PDF",
                            )
                        }
                    >
                        {exportingFormat ===
                            "PDF" ? (
                            <Loader2
                                className={
                                    styles.spin
                                }
                                size={17}
                            />
                        ) : (
                            <Download
                                size={17}
                            />
                        )}

                        {exportingFormat ===
                            "PDF"
                            ? "Gerando PDF..."
                            : "Baixar PDF"}
                    </button>

                    <button
                        type="button"
                        className={
                            styles.printButton
                        }
                        disabled={
                            exportingFormat !==
                            null
                        }
                        onClick={
                            handlePrint
                        }
                    >
                        <Printer
                            size={18}
                        />

                        Imprimir
                    </button>
                </div>
            </div>

            {exportError && (
                <div
                    className={
                        styles.exportError
                    }
                    role="alert"
                >
                    <CircleAlert
                        size={19}
                    />

                    <span>
                        {exportError}
                    </span>
                </div>
            )}

            {exportSuccess && (
                <div
                    className={
                        styles.exportSuccess
                    }
                    role="status"
                >
                    <CheckCircle2
                        size={19}
                    />

                    <span>
                        {exportSuccess}
                    </span>
                </div>
            )}

            <article
                className={
                    styles.document
                }
            >
                <header
                    className={
                        styles.printHeader
                    }
                >
                    <span>
                        {
                            selectedRevision.title
                        }
                    </span>

                    <strong>
                        Revisão{" "}
                        {
                            selectedRevision.version
                        }
                    </strong>
                </header>

                <footer
                    className={
                        styles.printFooter
                    }
                >
                    <span>
                        Hash:{" "}
                        {shortenHash(
                            selectedRevision.integrityHash,
                        )}
                    </span>

                    <span
                        className={
                            styles.pageNumber
                        }
                    />
                </footer>

                {showDraftWatermark && (
                    <div
                        className={
                            styles.watermark
                        }
                    >
                        {selectedRevision.status ===
                            "IN_REVIEW"
                            ? "EM REVISÃO"
                            : "RASCUNHO"}
                    </div>
                )}

                <section
                    className={
                        styles.coverPage
                    }
                >
                    <div
                        className={
                            styles.coverTop
                        }
                    >
                        <FileText
                            size={44}
                        />

                        <span>
                            Laudo Pericial Contábil
                        </span>
                    </div>

                    <div
                        className={
                            styles.coverContent
                        }
                    >
                        <p
                            className={
                                styles.coverEyebrow
                            }
                        >
                            Documento técnico
                        </p>

                        <h1>
                            {
                                selectedRevision.title
                            }
                        </h1>

                        {selectedRevision.reportNumber && (
                            <strong
                                className={
                                    styles.reportNumber
                                }
                            >
                                Laudo nº{" "}
                                {
                                    selectedRevision.reportNumber
                                }
                            </strong>
                        )}

                        <div
                            className={
                                styles.coverDivider
                            }
                        />

                        <div
                            className={
                                styles.coverInformation
                            }
                        >
                            <div>
                                <span>
                                    Processo
                                </span>

                                <strong>
                                    {report.legalProcess
                                        ?.caseNumber ??
                                        report.legalProcess
                                            ?.title ??
                                        "Não vinculado"}
                                </strong>
                            </div>

                            <div>
                                <span>
                                    Interessado
                                </span>

                                <strong>
                                    {report.client
                                        ?.name ??
                                        "Não informado"}
                                </strong>
                            </div>

                            <div>
                                <span>
                                    Cálculo utilizado
                                </span>

                                <strong>
                                    {calculationLink
                                        ?.calculation
                                        .title ??
                                        calculationType ??
                                        "Não informado"}
                                </strong>
                            </div>

                            <div>
                                <span>
                                    Versão do cálculo
                                </span>

                                <strong>
                                    {calculationLink
                                        ?.calculationRevision
                                        .version ??
                                        "—"}
                                </strong>
                            </div>
                        </div>
                    </div>

                    <div
                        className={
                            styles.coverBottom
                        }
                    >
                        <span>
                            {selectedRevision.place ??
                                report.place ??
                                "Local não informado"}
                        </span>

                        <strong>
                            {formatDate(
                                selectedRevision.referenceDate ??
                                report.referenceDate,
                            )}
                        </strong>

                        <small>
                            {coverSection?.plainText
                                ? "Documento gerado a partir dos dados versionados do sistema."
                                : "Documento técnico em preparação."}
                        </small>
                    </div>
                </section>

                <section
                    className={
                        styles.documentControl
                    }
                >
                    <div
                        className={
                            styles.controlHeader
                        }
                    >
                        <ShieldCheck
                            size={22}
                        />

                        <div>
                            <span>
                                Controle documental
                            </span>

                            <h2>
                                Identificação da
                                revisão
                            </h2>
                        </div>
                    </div>

                    <div
                        className={
                            styles.controlGrid
                        }
                    >
                        <div>
                            <span>
                                Situação
                            </span>

                            <strong>
                                {getStatusLabel(
                                    selectedRevision.status,
                                )}
                            </strong>
                        </div>

                        <div>
                            <span>
                                Revisão do laudo
                            </span>

                            <strong>
                                {
                                    selectedRevision.version
                                }
                            </strong>
                        </div>

                        <div>
                            <span>
                                Modelo
                            </span>

                            <strong>
                                {
                                    selectedRevision.templateVersion
                                }
                            </strong>
                        </div>

                        <div>
                            <span>
                                Motor do cálculo
                            </span>

                            <strong>
                                {calculationLink
                                    ?.calculationRevision
                                    .engineVersion ??
                                    "Não informado"}
                            </strong>
                        </div>

                        <div>
                            <span>
                                Criado em
                            </span>

                            <strong>
                                {formatDateTime(
                                    selectedRevision.createdAt,
                                )}
                            </strong>
                        </div>

                        <div>
                            <span>
                                Atualizado em
                            </span>

                            <strong>
                                {formatDateTime(
                                    selectedRevision.updatedAt,
                                )}
                            </strong>
                        </div>
                    </div>

                    <div
                        className={
                            styles.fullHash
                        }
                    >
                        <span>
                            Hash de integridade da
                            revisão
                        </span>

                        <strong>
                            {selectedRevision.integrityHash ??
                                "Ainda não gerado"}
                        </strong>
                    </div>
                </section>

                {bodySections.map(
                    (section) => (
                        <section
                            key={
                                section.id
                            }
                            className={
                                styles.reportSection
                            }
                            data-type={
                                section.type
                            }
                        >
                            <header
                                className={
                                    styles.sectionHeader
                                }
                            >
                                <span>
                                    Seção{" "}
                                    {
                                        section.position
                                    }
                                </span>

                                <h2>
                                    {
                                        section.title
                                    }
                                </h2>
                            </header>

                            {section.type ===
                                "CALCULATIONS" ? (
                                <>
                                    {renderText(
                                        section.plainText,
                                    )}

                                    {calculationLines.length >
                                        0 ? (
                                        <div
                                            className={
                                                styles.tableWrapper
                                            }
                                        >
                                            <table>
                                                <thead>
                                                    <tr>
                                                        {lineColumns.map(
                                                            (
                                                                column,
                                                            ) => (
                                                                <th
                                                                    key={
                                                                        column.id
                                                                    }
                                                                >
                                                                    {
                                                                        column.label
                                                                    }
                                                                </th>
                                                            ),
                                                        )}
                                                    </tr>
                                                </thead>

                                                <tbody>
                                                    {calculationLines.map(
                                                        (
                                                            line,
                                                            lineIndex,
                                                        ) => (
                                                            <tr
                                                                key={
                                                                    typeof line.id ===
                                                                        "string"
                                                                        ? line.id
                                                                        : `line-${lineIndex}`
                                                                }
                                                            >
                                                                {lineColumns.map(
                                                                    (
                                                                        column,
                                                                    ) => (
                                                                        <td
                                                                            key={
                                                                                column.id
                                                                            }
                                                                        >
                                                                            {formatColumnValue(
                                                                                column.getValue(
                                                                                    line,
                                                                                ),
                                                                                column.kind,
                                                                                currency,
                                                                            )}
                                                                        </td>
                                                                    ),
                                                                )}
                                                            </tr>
                                                        ),
                                                    )}
                                                </tbody>
                                            </table>
                                        </div>
                                    ) : (
                                        <p
                                            className={
                                                styles.emptyText
                                            }
                                        >
                                            Nenhuma linha detalhada foi registrada para esta revisão.
                                        </p>
                                    )}
                                </>
                            ) : (
                                renderText(
                                    section.plainText,
                                )
                            )}

                            {section.type ===
                                "SIGNATURE" && (
                                    <div
                                        className={
                                            styles.signatureArea
                                        }
                                    >
                                        <div
                                            className={
                                                styles.signatureLine
                                            }
                                        />

                                        <span>
                                            Assinatura do profissional responsável
                                        </span>
                                    </div>
                                )}
                        </section>
                    ),
                )}

                <section
                    className={
                        styles.finalIntegrity
                    }
                >
                    <ShieldCheck
                        size={24}
                    />

                    <div>
                        <h2>
                            Integridade e
                            rastreabilidade
                        </h2>

                        <p>
                            Este documento foi
                            elaborado a partir da
                            revisão{" "}
                            {
                                calculationLink
                                    ?.calculationRevision
                                    .version
                            }{" "}
                            do cálculo e da revisão{" "}
                            {
                                selectedRevision.version
                            }{" "}
                            do laudo. Alterações
                            posteriores exigem nova
                            revisão.
                        </p>

                        <strong>
                            Hash do laudo:{" "}
                            {selectedRevision.integrityHash ??
                                "não disponível"}
                        </strong>
                    </div>
                </section>
            </article>
        </div>
    );
}