// src/lib/reports/expert-report.schema.ts

import { z } from "zod";

export type ReportJsonValue =
    | string
    | number
    | boolean
    | null
    | ReportJsonValue[]
    | {
        [key: string]: ReportJsonValue;
    };

const optionalText = (
    maximumLength: number,
) =>
    z.preprocess(
        (value) => {
            if (
                typeof value === "string" &&
                value.trim() === ""
            ) {
                return undefined;
            }

            return value;
        },
        z
            .string()
            .trim()
            .max(maximumLength)
            .optional(),
    );

const requiredText = (
    fieldName: string,
    maximumLength: number,
) =>
    z
        .string()
        .trim()
        .min(
            1,
            `${fieldName} é obrigatório.`,
        )
        .max(maximumLength);

const isoDateSchema = z
    .string()
    .regex(
        /^\d{4}-\d{2}-\d{2}$/,
        "Informe uma data válida.",
    )
    .refine((value) => {
        const date = new Date(
            `${value}T12:00:00.000Z`,
        );

        return !Number.isNaN(
            date.getTime(),
        );
    }, "Informe uma data válida.");

export const reportJsonValueSchema: z.ZodType<ReportJsonValue> =
    z.lazy(() =>
        z.union([
            z.string(),
            z.number().finite(),
            z.boolean(),
            z.null(),
            z.array(reportJsonValueSchema),
            z.record(
                z.string(),
                reportJsonValueSchema,
            ),
        ]),
    );

export const reportSectionTypeSchema =
    z.enum([
        "COVER",
        "IDENTIFICATION",
        "PARTIES",
        "EXPERTISE_OBJECT",
        "CASE_SUMMARY",
        "ANALYZED_DOCUMENTS",
        "PREMISES",
        "METHODOLOGY",
        "INPUT_DATA",
        "FORMULAS",
        "CALCULATIONS",
        "RESULTS",
        "QUESTIONS",
        "CONCLUSION",
        "CLOSING",
        "SIGNATURE",
        "CUSTOM",
    ]);

export const reportRevisionStatusSchema =
    z.enum([
        "DRAFT",
        "IN_REVIEW",
    ]);

export const expertReportCreateSchema =
    z.object({
        calculationId: requiredText(
            "O cálculo",
            191,
        ),

        calculationVersion: z
            .number()
            .int()
            .positive()
            .optional(),

        title: optionalText(250),

        reportNumber: optionalText(100),

        purpose: optionalText(10000),

        referenceDate:
            isoDateSchema.optional(),

        place: optionalText(250),

        notes: optionalText(10000),
    });

export const expertReportSectionSchema =
    z.object({
        id: optionalText(191),

        type: reportSectionTypeSchema,

        title: requiredText(
            "O título da seção",
            250,
        ),

        plainText: optionalText(50000),

        content:
            reportJsonValueSchema.optional(),

        position: z
            .number()
            .int()
            .nonnegative(),

        isVisible:
            z.boolean().default(true),

        isAutoGenerated:
            z.boolean().default(false),
    });

export const expertReportRevisionUpdateSchema =
    z.object({
        title: requiredText(
            "O título",
            250,
        ),

        reportNumber: optionalText(100),

        purpose: optionalText(10000),

        referenceDate:
            isoDateSchema.optional(),

        place: optionalText(250),

        notes: optionalText(10000),

        status:
            reportRevisionStatusSchema.default(
                "DRAFT",
            ),

        sections: z
            .array(
                expertReportSectionSchema,
            )
            .min(
                1,
                "O laudo deve possuir pelo menos uma seção.",
            ),
    });

export type ExpertReportCreateInput =
    z.infer<
        typeof expertReportCreateSchema
    >;

export type ExpertReportSectionInput =
    z.infer<
        typeof expertReportSectionSchema
    >;

export type ExpertReportRevisionUpdateInput =
    z.infer<
        typeof expertReportRevisionUpdateSchema
    >;