// src/lib/reports/expert-report-template.ts

import {
    ReportSectionType,
} from "@prisma/client";

import {
    type CanonicalJson,
} from "./expert-report-hash";

export const EXPERT_REPORT_TEMPLATE_VERSION =
    "expert-report-1.0.0";

export type ExpertReportSectionDraft = {
    type: ReportSectionType;
    title: string;
    plainText: string | null;
    content: CanonicalJson | null;
    position: number;
    isVisible: boolean;
    isAutoGenerated: boolean;
};

type ExpertReportTemplateInput = {
    reportTitle: string;
    reportNumber: string | null;
    purpose: string | null;
    referenceDate: string | null;
    place: string | null;

    calculation: {
        id: string;
        type: string;
        title: string | null;
        description: string | null;
        currency: string;
    };

    revision: {
        id: string;
        version: number;
        engineVersion: string;
        integrityHash: string | null;
        input: CanonicalJson;
        premises: CanonicalJson | null;
        methodology: CanonicalJson | null;
        formulas: CanonicalJson | null;
        result: CanonicalJson;
        summary: CanonicalJson | null;
        warnings: CanonicalJson | null;
        lines: CanonicalJson;
    };

    clientSnapshot:
    | CanonicalJson
    | null;

    legalProcessSnapshot:
    | CanonicalJson
    | null;

    professionalSnapshot:
    | CanonicalJson
    | null;

    questionsSnapshot:
    | CanonicalJson
    | null;

    sourceDocumentsSnapshot:
    | CanonicalJson
    | null;
};

function isJsonObject(
    value: CanonicalJson | null,
): value is Record<
    string,
    CanonicalJson
> {
    return (
        value !== null &&
        typeof value === "object" &&
        !Array.isArray(value)
    );
}

function getString(
    value: CanonicalJson | null,
    key: string,
) {
    if (!isJsonObject(value)) {
        return null;
    }

    const item = value[key];

    return typeof item === "string"
        ? item
        : null;
}

function formatLabel(
    value: string,
) {
    const labels: Record<
        string,
        string
    > = {
        principal: "Valor principal",
        capital: "Capital",
        amount: "Montante",
        interest: "Juros",
        rate: "Taxa",
        period: "Período",
        periods: "Períodos",
        rateUnit: "Unidade da taxa",
        periodUnit:
            "Unidade do período",
        presentValue:
            "Valor presente",
        futureValue:
            "Valor futuro",
        totalInterest:
            "Total de juros",
        totalPaid: "Total pago",
        totalEntries:
            "Total de entradas",
        totalExits:
            "Total de saídas",
        balance: "Saldo",
        finalBalance:
            "Saldo final",
        netTotal:
            "Total líquido",
        grossTotal:
            "Total bruto",
        monetaryCorrection:
            "Correção monetária",
        correctedPrincipal:
            "Principal corrigido",
        moraInterest:
            "Juros de mora",
        attorneyFees:
            "Honorários",
        costs:
            "Custas e despesas",
        description:
            "Descrição",
        methodology:
            "Metodologia",
        warning: "Aviso",
    };

    if (labels[value]) {
        return labels[value];
    }

    return value
        .replace(
            /([A-Z])/g,
            " $1",
        )
        .replace(/[_-]+/g, " ")
        .replace(
            /^./,
            (letter) =>
                letter.toUpperCase(),
        );
}

function formatPrimitive(
    value:
        | string
        | number
        | boolean
        | null,
) {
    if (value === null) {
        return "Não informado";
    }

    if (typeof value === "boolean") {
        return value
            ? "Sim"
            : "Não";
    }

    return String(value);
}

function formatJsonAsText(
    value: CanonicalJson | null,
    level = 0,
): string {
    if (value === null) {
        return "Nenhuma informação registrada.";
    }

    if (
        typeof value === "string" ||
        typeof value === "number" ||
        typeof value === "boolean"
    ) {
        return formatPrimitive(value);
    }

    const indentation = "  ".repeat(
        level,
    );

    if (Array.isArray(value)) {
        if (value.length === 0) {
            return "Nenhuma informação registrada.";
        }

        return value
            .map(
                (item, index) =>
                    `${indentation}${index + 1}. ${formatJsonAsText(
                        item,
                        level + 1,
                    )}`,
            )
            .join("\n");
    }

    const entries =
        Object.entries(value);

    if (entries.length === 0) {
        return "Nenhuma informação registrada.";
    }

    return entries
        .map(([key, item]) => {
            const formattedLabel =
                formatLabel(key);

            if (
                item !== null &&
                typeof item ===
                "object"
            ) {
                return `${indentation}${formattedLabel}:\n${formatJsonAsText(
                    item,
                    level + 1,
                )}`;
            }

            return `${indentation}${formattedLabel}: ${formatJsonAsText(
                item,
                level + 1,
            )}`;
        })
        .join("\n");
}

function findNumericResult(
    value: CanonicalJson | null,
) {
    if (!isJsonObject(value)) {
        return null;
    }

    const preferredKeys = [
        "netTotal",
        "finalBalance",
        "balance",
        "finalAmount",
        "futureValue",
        "presentValue",
        "amount",
        "grossTotal",
        "totalPaid",
    ];

    for (const key of preferredKeys) {
        const item = value[key];

        if (
            typeof item === "number" &&
            Number.isFinite(item)
        ) {
            return {
                key,
                value: item,
            };
        }

        if (
            typeof item === "string"
        ) {
            const numericValue =
                Number(item);

            if (
                Number.isFinite(
                    numericValue,
                )
            ) {
                return {
                    key,
                    value: numericValue,
                };
            }
        }
    }

    return null;
}

function formatCurrency(
    value: number,
    currency: string,
) {
    return new Intl.NumberFormat(
        "pt-BR",
        {
            style: "currency",
            currency,
        },
    ).format(value);
}

function buildConclusion(
    input: ExpertReportTemplateInput,
) {
    const mainResult =
        findNumericResult(
            input.revision.summary,
        ) ??
        findNumericResult(
            input.revision.result,
        );

    if (!mainResult) {
        return [
            "Com base nos dados disponibilizados, nas premissas adotadas e na metodologia descrita neste laudo, foram obtidos os resultados apresentados na memória de cálculo.",
            "A conclusão deverá ser revisada e complementada pelo profissional responsável antes da finalização do documento.",
        ].join("\n\n");
    }

    return [
        "Com base nos dados disponibilizados, nas premissas adotadas e na metodologia descrita neste laudo, conclui-se que o resultado principal da apuração corresponde a:",
        `${formatLabel(
            mainResult.key,
        )}: ${formatCurrency(
            mainResult.value,
            input.calculation.currency,
        )}.`,
        "O valor deverá ser interpretado em conjunto com as ressalvas, critérios, fórmulas e limitações descritas nas demais seções.",
        "Esta conclusão é inicialmente gerada pelo sistema e deverá ser revisada pelo profissional responsável antes da finalização.",
    ].join("\n\n");
}

function buildSignatureText(
    professionalSnapshot:
        | CanonicalJson
        | null,
) {
    const signatureName =
        getString(
            professionalSnapshot,
            "signatureName",
        ) ??
        getString(
            professionalSnapshot,
            "fullName",
        ) ??
        "Profissional responsável";

    const signatureTitle =
        getString(
            professionalSnapshot,
            "signatureTitle",
        ) ??
        "Perito Contábil";

    const crcNumber = getString(
        professionalSnapshot,
        "crcNumber",
    );

    const crcState = getString(
        professionalSnapshot,
        "crcState",
    );

    const crcText = crcNumber
        ? `CRC${crcState
            ? `/${crcState}`
            : ""
        } ${crcNumber}`
        : "CRC não informado";

    return [
        signatureName,
        signatureTitle,
        crcText,
    ].join("\n");
}

export function buildInitialExpertReportSections(
    input: ExpertReportTemplateInput,
): ExpertReportSectionDraft[] {
    const processTitle =
        getString(
            input.legalProcessSnapshot,
            "title",
        );

    const caseNumber =
        getString(
            input.legalProcessSnapshot,
            "caseNumber",
        );

    const clientName =
        getString(
            input.clientSnapshot,
            "name",
        );

    const expertiseObject =
        getString(
            input.legalProcessSnapshot,
            "expertiseObject",
        );

    const reportClosingText =
        getString(
            input.professionalSnapshot,
            "reportClosingText",
        );

    return [
        {
            type: ReportSectionType.COVER,
            title: input.reportTitle,
            plainText: [
                "LAUDO PERICIAL CONTÁBIL",
                input.reportNumber
                    ? `Laudo nº ${input.reportNumber}`
                    : "Número do laudo ainda não informado",
                caseNumber
                    ? `Processo nº ${caseNumber}`
                    : "Processo não vinculado",
                clientName
                    ? `Interessado: ${clientName}`
                    : "Interessado não informado",
                input.place ??
                "Local não informado",
                input.referenceDate ??
                "Data-base não informada",
            ].join("\n"),
            content: {
                reportTitle:
                    input.reportTitle,
                reportNumber:
                    input.reportNumber,
                caseNumber,
                clientName,
                place: input.place,
                referenceDate:
                    input.referenceDate,
            },
            position: 0,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.IDENTIFICATION,
            title:
                "1. Identificação do laudo",
            plainText: [
                `Título: ${input.reportTitle}`,
                `Cálculo: ${input.calculation.title ??
                input.calculation.type
                }`,
                `Versão do cálculo: ${input.revision.version}`,
                `Motor de cálculo: ${input.revision.engineVersion}`,
                `Hash do cálculo: ${input.revision.integrityHash ??
                "não informado"
                }`,
            ].join("\n"),
            content: {
                reportTitle:
                    input.reportTitle,
                reportNumber:
                    input.reportNumber,
                calculationId:
                    input.calculation.id,
                calculationTitle:
                    input.calculation.title,
                calculationType:
                    input.calculation.type,
                calculationRevisionId:
                    input.revision.id,
                calculationVersion:
                    input.revision.version,
                engineVersion:
                    input.revision.engineVersion,
                calculationIntegrityHash:
                    input.revision
                        .integrityHash,
            },
            position: 1,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.PARTIES,
            title:
                "2. Identificação das partes",
            plainText:
                formatJsonAsText(
                    input.clientSnapshot,
                ),
            content:
                input.clientSnapshot,
            position: 2,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.EXPERTISE_OBJECT,
            title:
                "3. Objeto da perícia",
            plainText:
                expertiseObject ??
                input.purpose ??
                input.calculation
                    .description ??
                "Descrever o objeto da perícia e a questão técnica submetida à análise.",
            content: {
                expertiseObject,
                purpose: input.purpose,
                calculationDescription:
                    input.calculation
                        .description,
            },
            position: 3,
            isVisible: true,
            isAutoGenerated: false,
        },

        {
            type:
                ReportSectionType.CASE_SUMMARY,
            title:
                "4. Síntese processual",
            plainText: processTitle
                ? [
                    `Processo: ${processTitle}`,
                    caseNumber
                        ? `Número: ${caseNumber}`
                        : null,
                    "",
                    formatJsonAsText(
                        input.legalProcessSnapshot,
                    ),
                ]
                    .filter(
                        (
                            item,
                        ): item is string =>
                            item !== null,
                    )
                    .join("\n")
                : "Nenhum processo foi vinculado ao cálculo. Esta seção deverá ser revisada.",
            content:
                input.legalProcessSnapshot,
            position: 4,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.ANALYZED_DOCUMENTS,
            title:
                "5. Documentos analisados",
            plainText:
                formatJsonAsText(
                    input.sourceDocumentsSnapshot,
                ),
            content:
                input.sourceDocumentsSnapshot,
            position: 5,
            isVisible: true,
            isAutoGenerated: false,
        },

        {
            type:
                ReportSectionType.PREMISES,
            title:
                "6. Premissas e critérios adotados",
            plainText:
                formatJsonAsText(
                    input.revision.premises,
                ),
            content:
                input.revision.premises,
            position: 6,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.METHODOLOGY,
            title:
                "7. Metodologia",
            plainText:
                formatJsonAsText(
                    input.revision.methodology,
                ),
            content:
                input.revision.methodology,
            position: 7,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.INPUT_DATA,
            title:
                "8. Dados utilizados na apuração",
            plainText:
                formatJsonAsText(
                    input.revision.input,
                ),
            content:
                input.revision.input,
            position: 8,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.FORMULAS,
            title:
                "9. Fórmulas e substituições numéricas",
            plainText:
                formatJsonAsText(
                    input.revision.formulas,
                ),
            content:
                input.revision.formulas,
            position: 9,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.CALCULATIONS,
            title:
                "10. Memória detalhada de cálculo",
            plainText:
                "A memória detalhada é composta pelas linhas vinculadas à versão selecionada do cálculo. As tabelas serão apresentadas integralmente na visualização e nas exportações.",
            content: {
                lines:
                    input.revision.lines,
                warnings:
                    input.revision
                        .warnings,
            },
            position: 10,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.RESULTS,
            title:
                "11. Resultados apurados",
            plainText:
                formatJsonAsText(
                    input.revision.result,
                ),
            content: {
                result:
                    input.revision.result,
                summary:
                    input.revision.summary,
            },
            position: 11,
            isVisible: true,
            isAutoGenerated: true,
        },

        {
            type:
                ReportSectionType.QUESTIONS,
            title:
                "12. Quesitos e respostas",
            plainText:
                formatJsonAsText(
                    input.questionsSnapshot,
                ),
            content:
                input.questionsSnapshot,
            position: 12,
            isVisible: true,
            isAutoGenerated: false,
        },

        {
            type:
                ReportSectionType.CONCLUSION,
            title:
                "13. Conclusão técnica",
            plainText:
                buildConclusion(input),
            content: {
                generatedConclusion:
                    buildConclusion(input),
                result:
                    input.revision.result,
                summary:
                    input.revision.summary,
            },
            position: 13,
            isVisible: true,
            isAutoGenerated: false,
        },

        {
            type:
                ReportSectionType.CLOSING,
            title:
                "14. Encerramento",
            plainText:
                reportClosingText ??
                "Encerra-se o presente Laudo Pericial Contábil, que deverá ser revisado, datado e assinado pelo profissional responsável.",
            content: {
                place: input.place,
                referenceDate:
                    input.referenceDate,
                closingText:
                    reportClosingText,
            },
            position: 14,
            isVisible: true,
            isAutoGenerated: false,
        },

        {
            type:
                ReportSectionType.SIGNATURE,
            title:
                "15. Identificação e assinatura do profissional",
            plainText:
                buildSignatureText(
                    input.professionalSnapshot,
                ),
            content:
                input.professionalSnapshot,
            position: 15,
            isVisible: true,
            isAutoGenerated: true,
        },
    ];
}