// src/lib/reports/expert-report-export.service.ts

import { createHash } from "node:crypto";

import {
    AuditAction,
    GeneratedDocumentStatus,
    GeneratedDocumentType,
} from "@prisma/client";

import { prisma } from "@/lib/prisma";

import {
    type CanonicalJson,
    toCanonicalJson,
} from "./expert-report-hash";
import {
    ExpertReportServiceError,
} from "./expert-report.service";

export type ExportJsonRecord =
    Record<string, CanonicalJson>;

export type ExpertReportExportSection = {
    id: string;
    type: string;
    title: string;
    plainText: string | null;
    content: CanonicalJson | null;
    position: number;
    isVisible: boolean;
    isAutoGenerated: boolean;
};

export type ExpertReportExportCalculation = {
    calculation: {
        id: string;
        type: string;
        title: string | null;
        description: string | null;
        currency: string;
    };

    revision: {
        id: string;
        version: number;
        engineVersion: string;
        integrityHash: string | null;
        referenceDate: string | null;
        lines: ExportJsonRecord[];
    };

    snapshot: CanonicalJson;
};

export type ExpertReportExportSource = {
    report: {
        id: string;
        title: string;
        reportNumber: string | null;
        status: string;
        currentVersion: number;
        purpose: string | null;
        referenceDate: string | null;
        place: string | null;
        issuedAt: string | null;
    };

    client: {
        id: string;
        name: string;
        tradeName: string | null;
        documentNumber: string | null;
    } | null;

    legalProcess: {
        id: string;
        caseNumber: string | null;
        title: string | null;
        court: string | null;
        courtDivision: string | null;
        district: string | null;
        city: string | null;
        state: string | null;
        actionClass: string | null;
        subject: string | null;
    } | null;

    revision: {
        id: string;
        version: number;
        status: string;
        title: string;
        reportNumber: string | null;
        purpose: string | null;
        referenceDate: string | null;
        place: string | null;
        issuedAt: string | null;
        templateVersion: string;
        integrityHash: string | null;
        notes: string | null;
        createdAt: string;
        updatedAt: string;

        sourceSnapshot: CanonicalJson;
        clientSnapshot: CanonicalJson | null;
        legalProcessSnapshot:
        CanonicalJson | null;
        professionalSnapshot:
        CanonicalJson | null;
        questionsSnapshot:
        CanonicalJson | null;
        sourceDocumentsSnapshot:
        CanonicalJson | null;

        sections:
        ExpertReportExportSection[];
    };

    calculations:
    ExpertReportExportCalculation[];
};

export type ExportLineColumnKind =
    | "text"
    | "number"
    | "money"
    | "percent"
    | "date";

export type ExportLineColumn = {
    id: string;
    label: string;
    kind: ExportLineColumnKind;
    always?: boolean;

    getValue: (
        line: ExportJsonRecord,
    ) => CanonicalJson | undefined;
};

type LoadExpertReportExportOptions = {
    userId: string;
    reportId: string;
    version: number;
};

type RegisterExpertReportExportOptions = {
    userId: string;
    source: ExpertReportExportSource;
    fileName: string;
    mimeType: string;
    buffer: Uint8Array;
    format: "PDF" | "DOCX";

    requestMetadata?: {
        ipAddress?: string | null;
        userAgent?: string | null;
    };
};

export function isExportJsonRecord(
    value: unknown,
): value is ExportJsonRecord {
    return (
        value !== null &&
        typeof value === "object" &&
        !Array.isArray(value)
    );
}

function toExportJsonRecord(
    value: unknown,
) {
    const normalized =
        toCanonicalJson(value);

    return isExportJsonRecord(
        normalized,
    )
        ? normalized
        : null;
}

function toExportJsonRecordArray(
    value: unknown,
) {
    const normalized =
        toCanonicalJson(value);

    if (!Array.isArray(normalized)) {
        return [];
    }

    return normalized.filter(
        isExportJsonRecord,
    );
}

export async function loadExpertReportExportSource({
    userId,
    reportId,
    version,
}: LoadExpertReportExportOptions): Promise<ExpertReportExportSource> {
    const report =
        await prisma.expertReport.findFirst({
            where: {
                id: reportId,
                userId,
                deletedAt: null,
            },

            include: {
                client: {
                    select: {
                        id: true,
                        name: true,
                        tradeName: true,
                        documentNumber:
                            true,
                    },
                },

                legalProcess: {
                    select: {
                        id: true,
                        caseNumber: true,
                        title: true,
                        court: true,
                        courtDivision:
                            true,
                        district: true,
                        city: true,
                        state: true,
                        actionClass: true,
                        subject: true,
                    },
                },

                revisions: {
                    where: {
                        version,
                    },

                    take: 1,

                    include: {
                        sections: {
                            orderBy: {
                                position:
                                    "asc",
                            },
                        },

                        calculationLinks: {
                            orderBy: {
                                position:
                                    "asc",
                            },

                            include: {
                                calculation: {
                                    select: {
                                        id: true,
                                        type: true,
                                        title: true,
                                        description:
                                            true,
                                        currency: true,
                                    },
                                },

                                calculationRevision:
                                {
                                    include:
                                    {
                                        lines: {
                                            orderBy:
                                            {
                                                sequence:
                                                    "asc",
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
        });

    if (!report) {
        throw new ExpertReportServiceError(
            "Laudo não encontrado.",
            404,
            "REPORT_NOT_FOUND",
        );
    }

    const revision =
        report.revisions[0];

    if (!revision) {
        throw new ExpertReportServiceError(
            `A revisão ${version} do laudo não foi encontrada.`,
            404,
            "REPORT_REVISION_NOT_FOUND",
        );
    }

    return {
        report: {
            id: report.id,
            title: report.title,
            reportNumber:
                report.reportNumber,
            status: report.status,
            currentVersion:
                report.currentVersion,
            purpose: report.purpose,

            referenceDate:
                report.referenceDate?.toISOString() ??
                null,

            place: report.place,

            issuedAt:
                report.issuedAt?.toISOString() ??
                null,
        },

        client: report.client,

        legalProcess:
            report.legalProcess,

        revision: {
            id: revision.id,
            version: revision.version,
            status: revision.status,
            title: revision.title,

            reportNumber:
                revision.reportNumber,

            purpose: revision.purpose,

            referenceDate:
                revision.referenceDate?.toISOString() ??
                null,

            place: revision.place,

            issuedAt:
                revision.issuedAt?.toISOString() ??
                null,

            templateVersion:
                revision.templateVersion,

            integrityHash:
                revision.integrityHash,

            notes: revision.notes,

            createdAt:
                revision.createdAt.toISOString(),

            updatedAt:
                revision.updatedAt.toISOString(),

            sourceSnapshot:
                toCanonicalJson(
                    revision.sourceSnapshot,
                ),

            clientSnapshot:
                revision.clientSnapshot ===
                    null
                    ? null
                    : toCanonicalJson(
                        revision.clientSnapshot,
                    ),

            legalProcessSnapshot:
                revision.legalProcessSnapshot ===
                    null
                    ? null
                    : toCanonicalJson(
                        revision.legalProcessSnapshot,
                    ),

            professionalSnapshot:
                revision.professionalSnapshot ===
                    null
                    ? null
                    : toCanonicalJson(
                        revision.professionalSnapshot,
                    ),

            questionsSnapshot:
                revision.questionsSnapshot ===
                    null
                    ? null
                    : toCanonicalJson(
                        revision.questionsSnapshot,
                    ),

            sourceDocumentsSnapshot:
                revision.sourceDocumentsSnapshot ===
                    null
                    ? null
                    : toCanonicalJson(
                        revision.sourceDocumentsSnapshot,
                    ),

            sections:
                revision.sections.map(
                    (section) => ({
                        id: section.id,
                        type: section.type,
                        title:
                            section.title,
                        plainText:
                            section.plainText,

                        content:
                            section.content ===
                                null
                                ? null
                                : toCanonicalJson(
                                    section.content,
                                ),

                        position:
                            section.position,

                        isVisible:
                            section.isVisible,

                        isAutoGenerated:
                            section.isAutoGenerated,
                    }),
                ),
        },

        calculations:
            revision.calculationLinks.map(
                (link) => ({
                    calculation: {
                        id:
                            link.calculation
                                .id,

                        type:
                            link.calculation
                                .type,

                        title:
                            link.calculation
                                .title,

                        description:
                            link.calculation
                                .description,

                        currency:
                            link.calculation
                                .currency,
                    },

                    revision: {
                        id:
                            link.calculationRevision
                                .id,

                        version:
                            link.calculationRevision
                                .version,

                        engineVersion:
                            link.calculationRevision
                                .engineVersion,

                        integrityHash:
                            link.calculationRevision
                                .integrityHash,

                        referenceDate:
                            link.calculationRevision
                                .referenceDate
                                ?.toISOString() ??
                            null,

                        lines:
                            link.calculationRevision
                                .lines.map(
                                    (
                                        line,
                                    ) =>
                                        toExportJsonRecord(
                                            line,
                                        ) ??
                                        {},
                                ),
                    },

                    snapshot:
                        toCanonicalJson(
                            link.snapshot,
                        ),
                }),
            ),
    };
}

export function getStringFromJson(
    value:
        | CanonicalJson
        | null,
    key: string,
) {
    if (!isExportJsonRecord(value)) {
        return null;
    }

    const item = value[key];

    if (
        typeof item === "string" ||
        typeof item === "number"
    ) {
        return String(item);
    }

    return null;
}

export function getProfessionalName(
    source: ExpertReportExportSource,
) {
    return (
        getStringFromJson(
            source.revision
                .professionalSnapshot,
            "signatureName",
        ) ??
        getStringFromJson(
            source.revision
                .professionalSnapshot,
            "fullName",
        ) ??
        "Profissional responsável"
    );
}

export function getProfessionalTitle(
    source: ExpertReportExportSource,
) {
    return (
        getStringFromJson(
            source.revision
                .professionalSnapshot,
            "signatureTitle",
        ) ??
        "Perito Contábil"
    );
}

export function getProfessionalCrc(
    source: ExpertReportExportSource,
) {
    const number =
        getStringFromJson(
            source.revision
                .professionalSnapshot,
            "crcNumber",
        );

    const state =
        getStringFromJson(
            source.revision
                .professionalSnapshot,
            "crcState",
        );

    if (!number) {
        return "CRC não informado";
    }

    return `CRC${state
            ? `/${state}`
            : ""
        } ${number}`;
}

export function formatExportDate(
    value: string | null,
) {
    if (!value) {
        return "Não informada";
    }

    const date = new Date(value);

    if (
        Number.isNaN(date.getTime())
    ) {
        return value;
    }

    return new Intl.DateTimeFormat(
        "pt-BR",
    ).format(date);
}

export function formatExportDateTime(
    value: string | null,
) {
    if (!value) {
        return "Não informado";
    }

    const date = new Date(value);

    if (
        Number.isNaN(date.getTime())
    ) {
        return value;
    }

    return new Intl.DateTimeFormat(
        "pt-BR",
        {
            dateStyle: "short",
            timeStyle: "short",
        },
    ).format(date);
}

export function formatExportMoney(
    value:
        | CanonicalJson
        | undefined,
    currency: string,
) {
    if (
        value === null ||
        value === undefined ||
        value === ""
    ) {
        return "—";
    }

    const numericValue =
        Number(value);

    if (
        !Number.isFinite(
            numericValue,
        )
    ) {
        return String(value);
    }

    return new Intl.NumberFormat(
        "pt-BR",
        {
            style: "currency",
            currency,
        },
    ).format(numericValue);
}

export function formatExportPercent(
    value:
        | CanonicalJson
        | undefined,
) {
    if (
        value === null ||
        value === undefined ||
        value === ""
    ) {
        return "—";
    }

    const numericValue =
        Number(value);

    if (
        !Number.isFinite(
            numericValue,
        )
    ) {
        return String(value);
    }

    const percentage =
        Math.abs(numericValue) <= 1
            ? numericValue * 100
            : numericValue;

    return `${new Intl.NumberFormat(
        "pt-BR",
        {
            minimumFractionDigits: 2,
            maximumFractionDigits: 6,
        },
    ).format(percentage)}%`;
}

export function formatExportPrimitive(
    value:
        | CanonicalJson
        | undefined,
) {
    if (
        value === null ||
        value === undefined ||
        value === ""
    ) {
        return "—";
    }

    if (typeof value === "boolean") {
        return value
            ? "Sim"
            : "Não";
    }

    if (
        typeof value === "object"
    ) {
        return JSON.stringify(value);
    }

    return String(value);
}

function getMetadataValue(
    line: ExportJsonRecord,
    key: string,
) {
    const metadata =
        line.metadata;

    if (!isExportJsonRecord(metadata)) {
        return undefined;
    }

    return metadata[key];
}

function hasExportValue(
    value:
        | CanonicalJson
        | undefined,
) {
    return (
        value !== undefined &&
        value !== null &&
        value !== ""
    );
}

function normalizeCalculationType(
    type: string,
) {
    return type
        .trim()
        .toUpperCase()
        .replace(/[\s-]+/g, "_");
}

export function getExportCalculationLines(
    source: ExpertReportExportSource,
) {
    const calculationsSection =
        source.revision.sections.find(
            (section) =>
                section.type ===
                "CALCULATIONS",
        );

    if (
        calculationsSection &&
        isExportJsonRecord(
            calculationsSection.content,
        )
    ) {
        const sectionLines =
            calculationsSection.content
                .lines;

        const parsedLines =
            toExportJsonRecordArray(
                sectionLines,
            );

        if (parsedLines.length > 0) {
            return parsedLines;
        }
    }

    return source.calculations.flatMap(
        (calculation) =>
            calculation.revision.lines,
    );
}

export function getExportLineColumns(
    calculationType: string,
    lines: ExportJsonRecord[],
): ExportLineColumn[] {
    const normalizedType =
        normalizeCalculationType(
            calculationType,
        );

    let columns: ExportLineColumn[];

    if (
        [
            "FLUXO_DE_CAIXA",
            "FLUXO_CAIXA",
        ].includes(normalizedType)
    ) {
        columns = [
            {
                id: "sequence",
                label: "#",
                kind: "number",
                always: true,

                getValue: (line) =>
                    line.sequence,
            },

            {
                id: "period",
                label: "Período",
                kind: "number",
                always: true,

                getValue: (line) =>
                    getMetadataValue(
                        line,
                        "period",
                    ),
            },

            {
                id: "label",
                label: "Descrição",
                kind: "text",
                always: true,

                getValue: (line) =>
                    line.label,
            },

            {
                id: "credit",
                label: "Entrada",
                kind: "money",

                getValue: (line) =>
                    line.credit,
            },

            {
                id: "debit",
                label: "Saída",
                kind: "money",

                getValue: (line) =>
                    line.debit,
            },

            {
                id: "openingBalance",
                label: "Saldo inicial",
                kind: "money",

                getValue: (line) =>
                    line.openingBalance,
            },

            {
                id: "closingBalance",
                label: "Saldo final",
                kind: "money",
                always: true,

                getValue: (line) =>
                    line.closingBalance,
            },
        ];
    } else if (
        normalizedType ===
        "ANALISE_PERICIAL"
    ) {
        columns = [
            {
                id: "sequence",
                label: "#",
                kind: "number",
                always: true,

                getValue: (line) =>
                    line.sequence,
            },

            {
                id: "label",
                label: "Etapa",
                kind: "text",
                always: true,

                getValue: (line) =>
                    line.label,
            },

            {
                id: "openingBalance",
                label: "Saldo inicial",
                kind: "money",

                getValue: (line) =>
                    line.openingBalance,
            },

            {
                id: "debit",
                label: "Adição",
                kind: "money",

                getValue: (line) =>
                    line.debit,
            },

            {
                id: "monetaryCorrection",
                label: "Correção",
                kind: "money",

                getValue: (line) =>
                    line.monetaryCorrection,
            },

            {
                id: "interest",
                label: "Juros",
                kind: "money",

                getValue: (line) =>
                    line.interest,
            },

            {
                id: "fine",
                label: "Multa",
                kind: "money",

                getValue: (line) =>
                    line.fine,
            },

            {
                id: "fee",
                label: "Honorários",
                kind: "money",

                getValue: (line) =>
                    line.fee,
            },

            {
                id: "payment",
                label: "Pagamento",
                kind: "money",

                getValue: (line) =>
                    line.payment ??
                    line.credit,
            },

            {
                id: "closingBalance",
                label: "Saldo final",
                kind: "money",
                always: true,

                getValue: (line) =>
                    line.closingBalance,
            },
        ];
    } else {
        columns = [
            {
                id: "sequence",
                label: "#",
                kind: "number",
                always: true,

                getValue: (line) =>
                    line.sequence,
            },

            {
                id: "label",
                label: "Descrição",
                kind: "text",
                always: true,

                getValue: (line) =>
                    line.label,
            },

            {
                id: "competence",
                label: "Competência",
                kind: "date",

                getValue: (line) =>
                    line.competence ??
                    line.dueDate,
            },

            {
                id: "openingBalance",
                label: "Saldo inicial",
                kind: "money",

                getValue: (line) =>
                    line.openingBalance,
            },

            {
                id: "correctionRate",
                label: "Correção %",
                kind: "percent",

                getValue: (line) =>
                    line.correctionRate,
            },

            {
                id: "monetaryCorrection",
                label: "Correção",
                kind: "money",

                getValue: (line) =>
                    line.monetaryCorrection,
            },

            {
                id: "interestRate",
                label: "Juros %",
                kind: "percent",

                getValue: (line) =>
                    line.interestRate,
            },

            {
                id: "interest",
                label: "Juros",
                kind: "money",

                getValue: (line) =>
                    line.interest,
            },

            {
                id: "amortization",
                label: "Amortização",
                kind: "money",

                getValue: (line) =>
                    line.amortization,
            },

            {
                id: "installment",
                label: "Prestação",
                kind: "money",

                getValue: (line) =>
                    line.installment,
            },

            {
                id: "payment",
                label: "Pagamento",
                kind: "money",

                getValue: (line) =>
                    line.payment,
            },

            {
                id: "closingBalance",
                label: "Saldo final",
                kind: "money",

                getValue: (line) =>
                    line.closingBalance,
            },
        ];
    }

    return columns.filter(
        (column) =>
            column.always ||
            lines.some((line) =>
                hasExportValue(
                    column.getValue(line),
                ),
            ),
    );
}

export function formatExportLineValue(
    value:
        | CanonicalJson
        | undefined,
    kind: ExportLineColumnKind,
    currency: string,
) {
    if (kind === "money") {
        return formatExportMoney(
            value,
            currency,
        );
    }

    if (kind === "percent") {
        return formatExportPercent(
            value,
        );
    }

    if (kind === "date") {
        return typeof value === "string"
            ? formatExportDate(value)
            : "—";
    }

    if (kind === "number") {
        if (
            value === null ||
            value === undefined ||
            value === ""
        ) {
            return "—";
        }

        const numericValue =
            Number(value);

        return Number.isFinite(
            numericValue,
        )
            ? new Intl.NumberFormat(
                "pt-BR",
            ).format(numericValue)
            : String(value);
    }

    return formatExportPrimitive(
        value,
    );
}

export function getVisibleExportSections(
    source: ExpertReportExportSource,
) {
    return [
        ...source.revision.sections,
    ]
        .filter(
            (section) =>
                section.isVisible,
        )
        .sort(
            (left, right) =>
                left.position -
                right.position,
        );
}

export function splitExportText(
    text: string | null,
) {
    if (!text?.trim()) {
        return [
            "Nenhum conteúdo informado nesta seção.",
        ];
    }

    return text
        .replace(/\r\n/g, "\n")
        .split("\n");
}

function sanitizeFileNamePart(
    value: string,
) {
    return value
        .normalize("NFD")
        .replace(
            /[\u0300-\u036f]/g,
            "",
        )
        .toLowerCase()
        .replace(
            /[^a-z0-9]+/g,
            "-",
        )
        .replace(
            /^-+|-+$/g,
            "",
        )
        .slice(0, 100);
}

export function getExpertReportExportFileName(
    source: ExpertReportExportSource,
    extension: "pdf" | "docx",
) {
    const base =
        source.revision.reportNumber
            ? `laudo-${source.revision.reportNumber}`
            : source.revision.title;

    const safeBase =
        sanitizeFileNamePart(base) ||
        "laudo-pericial";

    return `${safeBase}-revisao-${source.revision.version}.${extension}`;
}

export async function registerExpertReportExport({
    userId,
    source,
    fileName,
    mimeType,
    buffer,
    format,
    requestMetadata,
}: RegisterExpertReportExportOptions) {
    const integrityHash =
        createHash("sha256")
            .update(buffer)
            .digest("hex");

    const calculationRevisionId =
        source.calculations[0]
            ?.revision.id ??
        null;

    return prisma.$transaction(
        async (transaction) => {
            const document =
                await transaction.generatedDocument.create(
                    {
                        data: {
                            userId,

                            expertReportId:
                                source.report.id,

                            expertReportRevisionId:
                                source.revision.id,

                            calculationRevisionId,

                            type:
                                GeneratedDocumentType.EXPERT_REPORT,

                            status:
                                GeneratedDocumentStatus.READY,

                            fileName,

                            storageKey:
                                null,

                            mimeType,

                            sizeBytes:
                                buffer.byteLength,

                            integrityHash,

                            pageCount:
                                null,

                            templateVersion:
                                source.revision
                                    .templateVersion,

                            errorMessage:
                                null,

                            generatedAt:
                                new Date(),
                        },
                    },
                );

            await transaction.auditEvent.create({
                data: {
                    userId,

                    entityType:
                        "GeneratedDocument",

                    entityId:
                        document.id,

                    action:
                        AuditAction.GENERATE_DOCUMENT,

                    description: `${format} do laudo ${source.revision.title}, revisão ${source.revision.version}, gerado.`,

                    newData: {
                        generatedDocumentId:
                            document.id,

                        reportId:
                            source.report.id,

                        reportRevisionId:
                            source.revision.id,

                        reportVersion:
                            source.revision
                                .version,

                        fileName,
                        mimeType,

                        sizeBytes:
                            buffer.byteLength,

                        integrityHash,

                        templateVersion:
                            source.revision
                                .templateVersion,

                        storagePersisted:
                            false,
                    },

                    ipAddress:
                        requestMetadata?.ipAddress ??
                        null,

                    userAgent:
                        requestMetadata?.userAgent ??
                        null,
                },
            });

            await transaction.auditEvent.create({
                data: {
                    userId,

                    entityType:
                        "GeneratedDocument",

                    entityId:
                        document.id,

                    action:
                        AuditAction.DOWNLOAD_DOCUMENT,

                    description: `${format} do laudo ${source.revision.title}, revisão ${source.revision.version}, disponibilizado para download.`,

                    newData: {
                        generatedDocumentId:
                            document.id,

                        reportId:
                            source.report.id,

                        reportRevisionId:
                            source.revision.id,

                        reportVersion:
                            source.revision
                                .version,

                        fileName,
                        mimeType,
                    },

                    ipAddress:
                        requestMetadata?.ipAddress ??
                        null,

                    userAgent:
                        requestMetadata?.userAgent ??
                        null,
                },
            });

            return document;
        },
    );
}